// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/registry/v1/foundation_store.proto

package pbregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFoundationStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoundationStoreRequest) Reset() {
	*x = GetFoundationStoreRequest{}
	mi := &file_sf_registry_v1_foundation_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoundationStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoundationStoreRequest) ProtoMessage() {}

func (x *GetFoundationStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_registry_v1_foundation_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoundationStoreRequest.ProtoReflect.Descriptor instead.
func (*GetFoundationStoreRequest) Descriptor() ([]byte, []int) {
	return file_sf_registry_v1_foundation_store_proto_rawDescGZIP(), []int{0}
}

func (x *GetFoundationStoreRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type GetFoundationStoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// found is true when an entry exists for the requested deployment id.
	Found         bool                  `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Message       string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Entry         *FoundationStoreEntry `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoundationStoreResponse) Reset() {
	*x = GetFoundationStoreResponse{}
	mi := &file_sf_registry_v1_foundation_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoundationStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoundationStoreResponse) ProtoMessage() {}

func (x *GetFoundationStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_registry_v1_foundation_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoundationStoreResponse.ProtoReflect.Descriptor instead.
func (*GetFoundationStoreResponse) Descriptor() ([]byte, []int) {
	return file_sf_registry_v1_foundation_store_proto_rawDescGZIP(), []int{1}
}

func (x *GetFoundationStoreResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetFoundationStoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFoundationStoreResponse) GetEntry() *FoundationStoreEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type FoundationStoreEntry struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Network      string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	// Public gRPC endpoint for internet / unknown-network consumers,
	// e.g. "{deployment-id}.hs.acme.example:443"
	Endpoint     string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tls          bool   `protobuf:"varint,4,opt,name=tls,proto3" json:"tls,omitempty"`
	AuthRequired bool   `protobuf:"varint,5,opt,name=auth_required,json=authRequired,proto3" json:"auth_required,omitempty"`
	// Private gRPC endpoint for peered-VPC / internal-gateway consumers
	// (no NAT hairpin), e.g. "{deployment-id}.hs-internal.acme.example:9000"
	InternalEndpoint string `protobuf:"bytes,6,opt,name=internal_endpoint,json=internalEndpoint,proto3" json:"internal_endpoint,omitempty"`
	InternalTls      bool   `protobuf:"varint,7,opt,name=internal_tls,json=internalTls,proto3" json:"internal_tls,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FoundationStoreEntry) Reset() {
	*x = FoundationStoreEntry{}
	mi := &file_sf_registry_v1_foundation_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundationStoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundationStoreEntry) ProtoMessage() {}

func (x *FoundationStoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sf_registry_v1_foundation_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundationStoreEntry.ProtoReflect.Descriptor instead.
func (*FoundationStoreEntry) Descriptor() ([]byte, []int) {
	return file_sf_registry_v1_foundation_store_proto_rawDescGZIP(), []int{2}
}

func (x *FoundationStoreEntry) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *FoundationStoreEntry) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *FoundationStoreEntry) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *FoundationStoreEntry) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *FoundationStoreEntry) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

func (x *FoundationStoreEntry) GetInternalEndpoint() string {
	if x != nil {
		return x.InternalEndpoint
	}
	return ""
}

func (x *FoundationStoreEntry) GetInternalTls() bool {
	if x != nil {
		return x.InternalTls
	}
	return false
}

var File_sf_registry_v1_foundation_store_proto protoreflect.FileDescriptor

const file_sf_registry_v1_foundation_store_proto_rawDesc = "" +
	"\n" +
	"%sf/registry/v1/foundation_store.proto\x12\x0esf.registry.v1\"@\n" +
	"\x19GetFoundationStoreRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"\x88\x01\n" +
	"\x1aGetFoundationStoreResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x05entry\x18\x03 \x01(\v2$.sf.registry.v1.FoundationStoreEntryR\x05entry\"\xf8\x01\n" +
	"\x14FoundationStoreEntry\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x10\n" +
	"\x03tls\x18\x04 \x01(\bR\x03tls\x12#\n" +
	"\rauth_required\x18\x05 \x01(\bR\fauthRequired\x12+\n" +
	"\x11internal_endpoint\x18\x06 \x01(\tR\x10internalEndpoint\x12!\n" +
	"\finternal_tls\x18\a \x01(\bR\vinternalTls2\x8d\x01\n" +
	"\x1eFoundationStoreRegistryService\x12k\n" +
	"\x12GetFoundationStore\x12).sf.registry.v1.GetFoundationStoreRequest\x1a*.sf.registry.v1.GetFoundationStoreResponseBAZ?github.com/streamingfast/dregistry/pb/sf/registry/v1;pbregistryb\x06proto3"

var (
	file_sf_registry_v1_foundation_store_proto_rawDescOnce sync.Once
	file_sf_registry_v1_foundation_store_proto_rawDescData []byte
)

func file_sf_registry_v1_foundation_store_proto_rawDescGZIP() []byte {
	file_sf_registry_v1_foundation_store_proto_rawDescOnce.Do(func() {
		file_sf_registry_v1_foundation_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_registry_v1_foundation_store_proto_rawDesc), len(file_sf_registry_v1_foundation_store_proto_rawDesc)))
	})
	return file_sf_registry_v1_foundation_store_proto_rawDescData
}

var file_sf_registry_v1_foundation_store_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sf_registry_v1_foundation_store_proto_goTypes = []any{
	(*GetFoundationStoreRequest)(nil),  // 0: sf.registry.v1.GetFoundationStoreRequest
	(*GetFoundationStoreResponse)(nil), // 1: sf.registry.v1.GetFoundationStoreResponse
	(*FoundationStoreEntry)(nil),       // 2: sf.registry.v1.FoundationStoreEntry
}
var file_sf_registry_v1_foundation_store_proto_depIdxs = []int32{
	2, // 0: sf.registry.v1.GetFoundationStoreResponse.entry:type_name -> sf.registry.v1.FoundationStoreEntry
	0, // 1: sf.registry.v1.FoundationStoreRegistryService.GetFoundationStore:input_type -> sf.registry.v1.GetFoundationStoreRequest
	1, // 2: sf.registry.v1.FoundationStoreRegistryService.GetFoundationStore:output_type -> sf.registry.v1.GetFoundationStoreResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_registry_v1_foundation_store_proto_init() }
func file_sf_registry_v1_foundation_store_proto_init() {
	if File_sf_registry_v1_foundation_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_registry_v1_foundation_store_proto_rawDesc), len(file_sf_registry_v1_foundation_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_registry_v1_foundation_store_proto_goTypes,
		DependencyIndexes: file_sf_registry_v1_foundation_store_proto_depIdxs,
		MessageInfos:      file_sf_registry_v1_foundation_store_proto_msgTypes,
	}.Build()
	File_sf_registry_v1_foundation_store_proto = out.File
	file_sf_registry_v1_foundation_store_proto_goTypes = nil
	file_sf_registry_v1_foundation_store_proto_depIdxs = nil
}
