// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sf/registry/v1/foundation_store.proto

package pbregistry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoundationStoreRegistryService_GetFoundationStore_FullMethodName = "/sf.registry.v1.FoundationStoreRegistryService/GetFoundationStore"
)

// FoundationStoreRegistryServiceClient is the client API for FoundationStoreRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FoundationStoreRegistryService resolves a foundational-store deployment
// to its public and internal gRPC endpoints.
type FoundationStoreRegistryServiceClient interface {
	// GetFoundationStore looks up a single foundational-store entry by deployment id.
	GetFoundationStore(ctx context.Context, in *GetFoundationStoreRequest, opts ...grpc.CallOption) (*GetFoundationStoreResponse, error)
}

type foundationStoreRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoundationStoreRegistryServiceClient(cc grpc.ClientConnInterface) FoundationStoreRegistryServiceClient {
	return &foundationStoreRegistryServiceClient{cc}
}

func (c *foundationStoreRegistryServiceClient) GetFoundationStore(ctx context.Context, in *GetFoundationStoreRequest, opts ...grpc.CallOption) (*GetFoundationStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFoundationStoreResponse)
	err := c.cc.Invoke(ctx, FoundationStoreRegistryService_GetFoundationStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoundationStoreRegistryServiceServer is the server API for FoundationStoreRegistryService service.
// All implementations should embed UnimplementedFoundationStoreRegistryServiceServer
// for forward compatibility.
//
// FoundationStoreRegistryService resolves a foundational-store deployment
// to its public and internal gRPC endpoints.
type FoundationStoreRegistryServiceServer interface {
	// GetFoundationStore looks up a single foundational-store entry by deployment id.
	GetFoundationStore(context.Context, *GetFoundationStoreRequest) (*GetFoundationStoreResponse, error)
}

// UnimplementedFoundationStoreRegistryServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoundationStoreRegistryServiceServer struct{}

func (UnimplementedFoundationStoreRegistryServiceServer) GetFoundationStore(context.Context, *GetFoundationStoreRequest) (*GetFoundationStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFoundationStore not implemented")
}
func (UnimplementedFoundationStoreRegistryServiceServer) testEmbeddedByValue() {}

// UnsafeFoundationStoreRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoundationStoreRegistryServiceServer will
// result in compilation errors.
type UnsafeFoundationStoreRegistryServiceServer interface {
	mustEmbedUnimplementedFoundationStoreRegistryServiceServer()
}

func RegisterFoundationStoreRegistryServiceServer(s grpc.ServiceRegistrar, srv FoundationStoreRegistryServiceServer) {
	// If the following call pancis, it indicates UnimplementedFoundationStoreRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoundationStoreRegistryService_ServiceDesc, srv)
}

func _FoundationStoreRegistryService_GetFoundationStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFoundationStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoundationStoreRegistryServiceServer).GetFoundationStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoundationStoreRegistryService_GetFoundationStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoundationStoreRegistryServiceServer).GetFoundationStore(ctx, req.(*GetFoundationStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoundationStoreRegistryService_ServiceDesc is the grpc.ServiceDesc for FoundationStoreRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoundationStoreRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.registry.v1.FoundationStoreRegistryService",
	HandlerType: (*FoundationStoreRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFoundationStore",
			Handler:    _FoundationStoreRegistryService_GetFoundationStore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sf/registry/v1/foundation_store.proto",
}
